called setAddress on ledger login
ElrondNetwork/elrond-sdk-erdjs pull request #48
Opened 2021-08-10 12:20 UTC by bogdan-rosianu

Called `setAddress` when logging with Ledger with the specified index.
Also, removed `addressIndex` from the constructor

2021-08-10 12:34 UTC, SebastianMarian submitted a review, later dismissed

2021-08-10 12:44 UTC, ccorcoveanu requested changes
Please add an entry in the changelog, unreleased section, with a reference to this PR and note the breaking changes it introduces (you have an example in the release of v6.0.0)

2021-08-18 11:45 UTC, ccorcoveanu commented
@bogdan-rosianu The unreleased section is badly formatted. I know it's not your PR that affected this, but can we do it here so we won't end up merging it like this?
I will green this PR anyway in case we decide to fix the changelog in a follow up PR

2021-08-18 11:45 UTC, ccorcoveanu approved these changes

2021-08-18 12:20 UTC, ccorcoveanu approved these changes

2021-08-18 12:50 UTC, SebastianMarian approved these changes

2021-08-18 12:51 UTC, merged