Add fromPlainObject method to tx object and fix the extension provider sign/send tx responses
ElrondNetwork/elrond-sdk-erdjs pull request #72
Opened 2021-09-02 11:11 UTC by andreigiura

…r responses for send/sign

2021-09-02 11:34 UTC, ccorcoveanu submitted a review, later dismissed

2021-09-02 14:44 UTC, bogdan-rosianu requested changes

2021-09-02 14:46 UTC, andreigiura commented on CHANGELOG.md
> +    - Provider's send/sign transaction methonds responded with plainObject transactions instead of Transcation
fixed

2021-09-02 14:54 UTC, bogdan-rosianu submitted a review, later dismissed

2021-09-02 14:55 UTC, bogdan-rosianu approved these changes

2021-09-03 09:59 UTC, ccorcoveanu approved these changes

2021-09-03 09:59 UTC, merged